### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by MalteKiefer** [bubelov/coin-map-android#13]
I see there are a lot of commits since the last version.
Can you release a new version?

**Comment by bubelov** [comment]
@MalteKiefer I'll see what I can do. It needs a few changes to be usable, mostly related to transition to OSM and getting rid of Google Services. By release, do you mean GitHub release or Google Play/F-Droid release? The app is not ready for app stores yet but I think I can prepare a GitHub release on weekend.

**Comment by MalteKiefer** [comment]
Yeah thanks.
I mean for fdroid. It would be nice when Google Maps is removes so I can used it too.

**Comment by MalteKiefer** [comment]
Now I see only a empty start not more

**Comment by soratobukuroneko** [comment]
I don't have the gapps on my phone but microG, and some features doesn't work like registering or the notification area. Would be cool if the new version solve that

**Comment by bubelov** [comment]
@soratobukuroneko the new version uses OSM and has zero deps on Google services so it should work fine on any Android system.
