### ISSUE TITLE
Optimize layouts with ConstraintLayout

### ISSUE THREAD

**Issue by bubelov** [bubelov/coin-map-android#7]

**Comment by ivan9105** [comment]
I took this task. 
Igor, does this mean need to remake all the screens on use ConstraintLayout?
What approach is used to test the layout?
Do I need to configure the emulator and try check layout at different resolutions?
Is it enough?

**Comment by bubelov** [comment]
@ivan9105 yes, everything in the layout folder. Ideally, we should have flat view hierarchies to optimize for performance. Now we have a lot of nested views, that's why it makes sense to switch to **ConstrainLayout**. You can start with simple pieces of UI.
